version: "3"

services:
  twitter-listener:
    build: .
    container_name: twitter-listener
    env_file:
      - .env
    command:
      - sh
      - -c
      - |
        python main.py
    volumes:
      - ./output:/output
